version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/static"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/tools/photo_ingest"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/static"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
